### PR TITLE
Update garena checks for the new patch

### LINKED ISSUE #291: item sets not showing up in garena lol lcu
hi, championify detects the league client and runs per normal, but when i enter the game i don't see any other item sets other than "recommended". not sure if its an issue on your end?

### PR DESCRIPTION
**Pull request by hollowsxd**
Fix #291

### CODE REVIEW

**Comment by dustinblackman** [comment]
Ah, so this is the new path in garena? Brilliant, thanks! I'm unsure why the Travis builds failed, I've triggered a rerun. However it looks like you'll need to update the path manager tests with the new exe.

**Comment by hollowsxd** [comment]
@dustinblackman weird bcs I just forked it and pushes the changes and it seems to be working, maybe I overlook some things lol, I will take a look again and hopefully fix it :+1:

**Comment by dustinblackman** [comment]
I'd assume it's working, but it's just the tests need to be updated along with it. :) https://github.com/dustinblackman/Championify/blob/master/tests/path_manager.js#L83-L94

**Comment by hollowsxd** [comment]
@dustinblackman ah I see now, my bad

**Comment by hollowsxd** [comment]
I changed it again so that the root folder get selected instead of the Game folder, also updated the test

**Pull request merged**
